### ISSUE TITLE
[BUG] firstname and lastname is reversed for Eva Stockhammer in Fundraising Studio

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/sosync#10]
# Problem
Eva Stockhammer has a reversed name in Fundrasing Studio. The firstname and lastname in odoo is still correct.

# Info
Instanz: care
res.partner Eva Stockhammer was created with the id=747 by the sosyncer in FS-Online at -> 11. Januar 2017 19:23:31

She was created because of an FS-Token creation of here.

# Affected Partners
Approx 5 will be corrected by hand by Petra

**Comment by michaelkarrer81** [comment]
Problem sollte nur temporär aufgetreten sein. Es ist nicht sicher ob dieser Fehler erneut auftreten kann - jedoch geht Sebi davon aus das es eher nicht mehr passieren wird.

Falls der Fehler erneut auftritt sollte dieser Bug-Report wieder geöffnet werden.

**Comment by thecro** [comment]
wir haben das besprochen und auch als symptom eines bereits behobenen fehlers eingestuft
