### ISSUE TITLE
Expiry Date von Webcode-Hash wird nicht von Odoo nach FS gesynced

### ISSUE THREAD

**Issue by mforberich** [OpenAT/sosync#21]
Das Expiry-Date vom Webcode-Hash wurde in Odoo verlängert. Die Änderung wurde nicht zum FS gesynced

**Comment by thecro** [comment]
soll/muss das noch im syncer v1 integriert werden?

**Comment by mforberich** [comment]
Meines Erachtens nicht. Die Zeit lieber investieren um die SyncFlows in V2 umzusetzen, sodass wir alle auf v2 upgraden können.
