### ISSUE TITLE
Fields with empty strings must be synced as boolean False from FS to FSO !

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/sosync#23]
Char fields with empty strings e.g.: "" must be synced as ```boolean False``` from FS to FSO.

In generell empty Fields must use the boolean ```False``` and not an empty string.

# Additional Info
If any Char field ist emptied odoo writes ```res.partner.write{'firstname': False}``` and not ```res.partner.write{'firstname': ''}```!

[Related odoo Issue](https://github.com/odoo/odoo/issues/7414)

**Comment by thecro** [comment]
already done earlier
