### ISSUE TITLE
Geburtsdatum manchmal um einen Tag verschoben

### ISSUE THREAD

**Issue by mforberich** [OpenAT/sosync#26]
Ich kann es nicht reproduzieren, aber mir ist aufgefallen, dass auffallend viele Geburtsdaten um einen Tag verschoben im BPKGebdaterzwungen-Feld aufscheinen. Sobald ich es wieder auf das Original-Gebdat stelle wird bei der ZMR-Abfrage sofort ein Treffer erzielt. Beispiele waren bei GL2K:
Christine Hammer
Susanne Walcher
In xaktionänderung ist auch gut zu sehen, dass viele Geburtsdaten um einen Tag geändert synchronisiert werden. Geben wirklich soviele Leute ihr Geburtsdatum um einen Tag versetzt an? Mir kommt das komisch vor.

**Comment by kaipm** [comment]
Hallo Marcus, das Problem habe ich am 10.08. behoben ([commit](https://github.com/OpenAT/sosync/commit/f6708a41745729a0f186d5ffa5eecd07962936ef)). Bezüglich Daten weiß ich nicht wie ich die selektieren soll, vielleicht haben Sebi oder Harald da eine Idee.
